spring:
    application:
        name: survey-generator
    data:
        mongodb:
            uri: mongodb://localhost/test
            database: test-webflux

    ai:
        azure:
            openai:
                api-key:
                endpoint:
                chat:
                    options:
                        deployment-name: gpt-5-nano
                        temperature: 1.0
#        ollama:
#            base-url: http://localhost:11434
#            chat:
#                options:
#                    model: gemma3

#aws:
#    s3:
#        bucket: initial-webflux
#    credentials:
#        access-key: ${AWS_ACCESS_KEY:default-access-key}
#        secret-key: ${AWS_SECRET_KEY:default-secret-key}
